name: utilities
description: A new Flutter package project.
version: 0.0.1
author: SinaMN75
homepage: SinaMN75.ir
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.1
  internet_connection_checker: ^0.0.1+1
  url_launcher: ^6.0.3
  get: ^4.1.4
  package_info: ^2.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  pull_to_refresh: ^2.0.0
  share: ^2.0.1
  image_gallery_saver: ^1.6.9
  flutter_rating_bar: ^4.0.0
  file_picker: ^3.0.1
  intl: ^0.17.0
  webview_flutter: ^2.0.4
  get_storage: ^2.0.2

dependency_overrides:
  path_provider: 2.0.1