name: utilities
description: A new Flutter package project.
version: 0.0.1
homepage: SinaMN75.com
publish_to: 'none'

environment:
  sdk: '>=2.17.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  url_launcher: ^6.0.15
  get: ^4.6.3
  package_info_plus: ^1.4.3+1
  share_plus: ^4.0.10
  file_picker: ^5.2.2
  intl: ^0.17.0
  webviewx: ^0.2.1
  get_storage: ^2.0.3
  flutter_svg: ^1.1.1+1
  persian_tools: ^1.0.1
  group_button: ^5.2.0
  image_cropper: ^3.0.0
  cached_network_image: ^3.2.1
  video_player: ^2.4.6
  just_audio: ^0.9.27
  syncfusion_flutter_pdfviewer: ^20.1.55-beta
  path_provider: ^2.0.11
  flutter_local_notifications: ^9.8.0+1
  flutter_easyloading: ^3.0.5
  pin_code_fields: ^7.4.0
  intl_phone_number_input: ^0.7.0+2
  flutter_image_compress: ^1.1.2
  dio: ^4.0.6


flutter:
  uses-material-design: true
  assets:
    - lib/assets/data/