name: utilities
description: A new Flutter package project.
version: 0.0.1
homepage: SinaMN75.ir
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  internet_connection_checker: ^0.0.1+1
  url_launcher: ^6.0.15
  get: ^4.3.8
  package_info: ^2.0.0
  carousel_slider: ^4.0.0
  pull_to_refresh: ^2.0.0
  share_plus: ^3.0.4
  flutter_rating_bar: ^4.0.0
  file_picker: ^4.2.4
  intl: ^0.17.0
  webview_flutter: ^2.0.13
  get_storage: ^2.0.2
  flutter_svg: ^0.23.0+1
  flutter_html: ^2.1.2
  persian_tools: ^1.0.1
  group_button: ^3.1.0
  smooth_page_indicator: ^1.0.0+2
  logger: ^1.1.0
#  app_settings: ^4.1.1