name: utilities
description: A new Flutter package project.
version: 0.0.1
homepage: SinaMN75.ir
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  internet_connection_checker: ^0.0.1+1
  url_launcher: ^6.0.15
  get: ^4.3.8
  package_info: ^2.0.0
  carousel_slider: ^4.0.0
  pull_to_refresh: ^2.0.0
  share_plus: ^3.0.4
  flutter_rating_bar: ^4.0.0
  file_picker: ^4.2.4
  intl: ^0.17.0
  webview_flutter: ^2.0.13
  get_storage: ^2.0.2
  flutter_svg: ^0.23.0+1
  flutter_html: ^2.1.2
  persian_tools: ^1.0.1
  group_button: ^3.1.0
  smooth_page_indicator: ^1.0.0+2
  logger: ^1.1.0
  image_cropper: ^1.4.1
#  app_settings: ^4.1.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/data/
    - lib/assets/fonts/

  fonts:
    - family: Ionicons
      fonts:
        - asset: lib/assets/fonts/Ionicons.ttf
    - family: AntDesign
      fonts:
        - asset: lib/assets/fonts/AntDesign.ttf
    - family: FontAwesome
      fonts:
        - asset: lib/assets/fonts/FontAwesome.ttf
    - family: MaterialIcons
      fonts:
        - asset: lib/assets/fonts/MaterialIcons.ttf
    - family: Entypo
      fonts:
        - asset: lib/assets/fonts/Entypo.ttf
    - family: EvilIcons
      fonts:
        - asset: lib/assets/fonts/EvilIcons.ttf
    - family: Feather
      fonts:
        - asset: lib/assets/fonts/Feather.ttf
    - family: Foundation
      fonts:
        - asset: lib/assets/fonts/Foundation.ttf
    - family: MaterialCommunityIcons
      fonts:
        - asset: lib/assets/fonts/MaterialCommunityIcons.ttf
    - family: Octicons
      fonts:
        - asset: lib/assets/fonts/Octicons.ttf
    - family: SimpleLineIcons
      fonts:
        - asset: lib/assets/fonts/SimpleLineIcons.ttf
    - family: Zocial
      fonts:
        - asset: lib/assets/fonts/Zocial.ttf
    - family: FontAwesome5
      fonts:
        - asset: lib/assets/fonts/FontAwesome5_Regular.ttf
    - family: FontAwesome5_Brands
      fonts:
        - asset: lib/assets/fonts/FontAwesome5_Brands.ttf
    - family: FontAwesome5_Solid
      fonts:
        - asset: lib/assets/fonts/FontAwesome5_Solid.ttf
    - family: WeatherIcons
      fonts:
        - asset: lib/assets/fonts/weathericons.ttf