name: utilities
description: A new Flutter package project.
version: 0.0.1
homepage: SinaMN75.com
publish_to: 'none'

environment:
  sdk: '>=2.17.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cached_network_image: ^3.2.1
  custom_sliding_segmented_control: ^1.7.3
  crypto: ^3.0.2

  dio: ^4.0.6
  dio_smart_retry: ^1.4.0
  dotted_border: ^2.0.0+3

  file_picker: ^5.2.4
  flutter_image_compress: ^1.1.2
  flutter_linkify: ^5.0.2
  fl_chart: ^0.55.2
  flick_video_player: ^0.5.0
  flutter_local_notifications: ^9.8.0+1
  flutter_easyloading: ^3.0.5
  flutter_svg: ^1.1.1+1

  get_storage: ^2.0.3
  group_button: ^5.2.0
  get: ^4.6.3

  intl: ^0.17.0
  image_cropper: ^3.0.0
  intl_phone_number_input: ^0.7.0+2

  just_audio: ^0.9.27

  local_auth: ^2.1.2
  local_auth_android: ^1.0.15
  local_auth_ios: ^1.0.10

  package_info_plus: ^1.4.3+1
  persian_tools: ^1.0.1
  path_provider: ^2.0.11
  provider: ^6.0.5
  pin_code_fields: ^7.4.0

  share_plus: ^4.0.10
  syncfusion_localizations: ^20.3.47
  syncfusion_flutter_datagrid_export: ^20.3.47-beta
  syncfusion_flutter_calendar: ^20.3.47
  syncfusion_flutter_datepicker: ^20.3.47
  syncfusion_flutter_charts: ^20.3.47
  syncfusion_flutter_gauges: ^20.3.47
  syncfusion_flutter_sliders: ^20.3.47
  syncfusion_flutter_pdf: ^20.3.47
  syncfusion_flutter_barcodes: ^20.3.47
  syncfusion_officechart: ^20.3.47-beta
  syncfusion_flutter_maps: ^20.3.47
  syncfusion_flutter_signaturepad: ^20.3.47
  syncfusion_flutter_pdfviewer: ^20.3.47-beta
  syncfusion_flutter_treemap: ^20.3.47-beta

  url_launcher: ^6.0.15

  video_player: ^2.4.6
  visibility_detector: ^0.3.3

  webviewx: ^0.2.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/data/